#!/usr/bin/env bash
set -euo pipefail

# To bootstrap the toolkit: ./bootstrap.sh
#
# Run this bootstrap script when installing the toolkit or after system reset.
# This will setup the necessary hooks to configure the environment.

# Toolkit for doing work in the terminal.
# I want to be able to bootstrap installing this.

BOOTSTRAP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG_DIR="$HOME/.config/toolkit"
ENV_TARGET="$CONFIG_DIR/env"
ZSHRC="$HOME/.zshrc"

mkdir -p "$CONFIG_DIR"

tk_log() {
	echo "[toolkit] $*"
}

tk_err() {
	echo "[toolkit] Error: $*" >&2
	exit 1
}

# Load existing configuration if it exists.
if [ -f "$ENV_TARGET" ]; then
    tk_log "Found existing configuration at $ENV_TARGET. Loading current settings..."
    set +u
    source "$ENV_TARGET"
    set -u
fi

prompt_config() {
    local var_name="$1"
    local prompt_desc="$2"
    local fallback_val="$3"

    # Read the current value from memory (handles unbound variables)
    local current_val=""
    if eval "[ -n \"\${$var_name+x}\" ]"; then
        current_val=$(eval "echo \"\$$var_name\"")
    fi

    local base_default="${current_val:-$fallback_val}"
    local user_input
    read -r -p "$prompt_desc [$base_default]: " user_input

    # Update the variable in running memory
    printf -v "$var_name" "%s" "${user_input:-$base_default}"
}

prompt_config "TOOLKIT_REMOTE"    "Toolkit Git Remote" "git@github.com:liamtbrand/toolkit.git"
prompt_config "CONFIG_REMOTE"     "Config Git Remote"  "git@github.com:liamtbrand/config.git"
prompt_config "PROFILE_REMOTE"    "Profile Git Remote" "git@github.com:liamtbrand/profile.git"
prompt_config "REPOS_DIR"         "Local Repos Folder" "$HOME/repos"
prompt_config "TOOLKIT_REPO_PATH" "Toolkit Repo Path"  "$REPOS_DIR/toolkit"
prompt_config "CONFIG_REPO_PATH"  "Config Repo Path"   "$REPOS_DIR/config.git"
prompt_config "PROFILE_REPO_PATH" "Profile Repo Path"  "$REPOS_DIR/profile.git"

{
    echo "# Toolkit Global Configuration (Generated on $(date))"
    echo "# DO NOT EDIT THIS FILE MANUALLY. Run bootstrap.sh to update."
    echo "export TOOLKIT_REMOTE=\"$TOOLKIT_REMOTE\""
    echo "export CONFIG_REMOTE=\"$CONFIG_REMOTE\""
    echo "export PROFILE_REMOTE=\"$PROFILE_REMOTE\""
    echo "export REPOS_DIR=\"$REPOS_DIR\""
    echo "export TOOLKIT_REPO_PATH=\"$TOOLKIT_REPO_PATH\""
    echo "export CONFIG_REPO_PATH=\"$CONFIG_REPO_PATH\""
    echo "export PROFILE_REPO_PATH=\"$PROFILE_REPO_PATH\""
    echo 'export PATH="$HOME/.local/bin:$PATH"'
} > "$ENV_TARGET"

source "$ENV_TARGET"

# If there is no directory for toolkit, clone it.
if [ ! -d "$TOOLKIT_REPO_PATH" ] ; then
	tk_log "toolkit not found at $TOOLKIT_REPO_PATH. cloning from upstream..."
	git clone "$TOOLKIT_REMOTE" "$TOOLKIT_REPO_PATH" || tk_err "Failed to clone from upstream."
else
	tk_log "toolkit found at $TOOLKIT_REPO_PATH"
fi

# Ensure toolkit is in fact toolkit
if ! git -C "$TOOLKIT_REPO_PATH" rev-parse --git-dir >/dev/null 2>&1 ; then
	tk_err "$TOOLKIT_REPO_PATH is not a valid git repository."
else
	tk_log "toolkit is a valid git repository."
fi

# Ensure toolkit remote is correctly set
if [ "$(git -C "$TOOLKIT_REPO_PATH" config --get remote.origin.url)" != "$TOOLKIT_REMOTE" ]; then
	tk_err "origin is not set to $TOOLKIT_REMOTE"
else
	tk_log "origin is correctly configured to $TOOLKIT_REMOTE"
fi

# Configure config.git
if [ ! -d "$CONFIG_REPO_PATH" ] ; then
    tk_log "config.git not found at $CONFIG_REPO_PATH. cloning from upstream..."
    git clone --bare "$CONFIG_REMOTE" "$CONFIG_REPO_PATH"
else
    tk_log "config found at $CONFIG_REPO_PATH"
fi

# Configure config.git init setup
config init

# =========================================================================== #
# Install dependencies

DEPENDENCIES_FILE="$BOOTSTRAP_DIR/dependencies.txt"

# Function to install dependencies
install_dependencies() {
    if [ ! -f "$DEPENDENCIES_FILE" ]; then
        tk_log "No $DEPENDENCIES_FILE found. Skipping dependency installation."
        return
    fi

    OS_TYPE=$(uname -s)

    if [ "$OS_TYPE" = "Darwin" ]; then
        tk_log "Detected macOS (Darwin). Installing dependencies via Homebrew..."

        if ! command -v brew &> /dev/null; then
            tk_err "Homebrew is not installed."
        fi

        # Safely read file line by line under strict mode
        while IFS= read -r package || [ -n "$package" ]; do
            [[ -z "$package" || "$package" =~ ^# ]] && continue

            # Skip if the command exists anywhere in your system PATH
            if command -v "$package" &> /dev/null; then
                tk_log "$package already exists on this system. Skipping..."
                continue
            fi

            tk_log "Installing $package via brew..."
            brew install "$package"
        done < "$DEPENDENCIES_FILE"

    elif [ "$OS_TYPE" = "Linux" ] && [ -f /etc/debian_version ]; then
        tk_log "Detected Ubuntu/Debian Linux. Installing dependencies via apt..."

        tk_log "Updating apt package list..."
        sudo apt update

        while IFS= read -r package || [ -n "$package" ]; do
            [[ -z "$package" || "$package" =~ ^# ]] && continue
            tk_log "Installing $package via apt..."
            sudo apt install -y "$package"
        done < "$DEPENDENCIES_FILE"
    else
	tk_err "Unsupported operating system. Skipping installations. Stopping bootstrap. FAILED"
    fi
}

# Run the dependency installer
install_dependencies

# =========================================================================== #
# Hook configuration

# Define the targets and hooks
PERSONAL_ZPROFILE="$HOME/.config/zsh/.zprofile.personal"
ZPROFILE_HOOK="[[ -f $PERSONAL_ZPROFILE ]] && source $PERSONAL_ZPROFILE"
if [ -f "$HOME/.config/zsh/.zprofile" ]; then
    ZPROFILE="$HOME/.config/zsh/.zprofile"
else
    ZPROFILE="$HOME/.zprofile"
fi

PERSONAL_ZSHRC="$HOME/.config/zsh/.zshrc.personal"
ZSHRC_HOOK="[[ -f $PERSONAL_ZSHRC ]] && source $PERSONAL_ZSHRC"
if [ -f "$HOME/.config/zsh/.zshrc" ]; then
    ZSHRC="$HOME/.config/zsh/.zshrc"
else
    ZSHRC="$HOME/.zshrc"
fi

# Function to safely add a hook to a file
add_hook() {
    local target_file="$1"
    local hook_line="$2"

    # Create the file if it doesn't exist
    if [ ! -f "$target_file" ]; then
        touch "$target_file"
	tk_log "Created $target_file"
    fi

    # Check if the hook is already there
    if grep -Fxq "$hook_line" "$target_file"; then
        tk_log "Hook already exists in $target_file"
    else
        # Append the hook to the end of the file
        echo -e "\n$hook_line" >> "$target_file"
        tk_log "Successfully added hook to $target_file"
    fi
}

# Hook in environment variables first
SOURCE_LINE="[[ -f \$HOME/.config/toolkit/env ]] && source \$HOME/.config/toolkit/env"
add_hook "$ZSHRC" "$SOURCE_LINE"

# Add the personal zprofile and zshrc hooks
add_hook "$ZPROFILE" "$ZPROFILE_HOOK"
add_hook "$ZSHRC" "$ZSHRC_HOOK"

# =========================================================================== #

BIN_TARGET="$HOME/.local/bin"
tk_log "Symlinking tools into $BIN_TARGET"

BIN_TARGET="$HOME/.local/bin"
mkdir -p "$BIN_TARGET"

ln -sf "$TOOLKIT_REPO_PATH/tools/config" "$BIN_TARGET"
ln -sf "$TOOLKIT_REPO_PATH/tools/profile" "$BIN_TARGET"
ln -sf "$TOOLKIT_REPO_PATH/tools/toolkit" "$BIN_TARGET"
ln -sf "$TOOLKIT_REPO_PATH/tools/repos" "$BIN_TARGET"
ln -sf "$TOOLKIT_REPO_PATH/tools/exifdiff" "$BIN_TARGET"
ln -sf "$TOOLKIT_REPO_PATH/tools/homelab" "$BIN_TARGET"
ln -sf "$TOOLKIT_REPO_PATH/tools/notes" "$BIN_TARGET"

tk_log "Bootstrap complete. To finalize, use config git status to review and update configuration."
tk_log "You will likely need to restore configuration if this is a new setup."
tk_log "Restart your shell to finish."
