#!/usr/bin/env bash
set -euo pipefail

# This tool is useful for making backups using rsync.
# It's a bit annoying to have to read the manual each time.
# This tool makes it easy to just point and shoot.
# Backup a directory using incremental backup facility of rsync between any two locations.
# Use sane defaults to make sure everything gets copied.
# Review this script and the rsync manual if you're unsure.

# Note: Some backups use old scripts.
# TODO: Build in a feature to identify old scripts and use those where possible?
# Maybe need to abort if an old script is detected?
# Ideally they'll all use the exact same script.

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    echo "ERROR: This script must be run, not sourced!" >&2
    # Use 'return' to stop execution within the sourced context
    exit 1
fi

if ! command -v date &> /dev/null; then
    echo "Error: 'date' is not installed. Aborting script." >&2
    exit 1
fi

if ! command -v rsync &> /dev/null; then
    echo "Error: 'rsync' is not installed. Aborting script." >&2
    exit 1
fi

# Assert rsync is a known version
RSYNC_HASHES=(
    "7a94e8a7473ba5f1e910a4b252719c6dea65603a364b34a73d815d493812d1b3" # rsync on macos
    "ea0f3606657eed1e998441ced3d545f5eec8082cdfb2ac04c985083c53aa3724" # rsync on synology NAS
)
RSYNC_PATH=$(type -p rsync)
if [[ -z "$RSYNC_PATH" ]]; then
    echo "Error: rsync not found in PATH."
    exit 1
fi
RSYNC_HASH=$(sha256sum "$RSYNC_PATH" | awk '{print $1}')
MATCH="false"
for hash in "${RSYNC_HASHES[@]}"; do
    if [[ "$RSYNC_HASH" == "$hash" ]]; then
	MATCH="true"
	break
    fi
done
if [[ "$MATCH" == "false" ]]; then
    echo "Warning: rsync binary hash ($RSYNC_HASH) is unknown. Aborting."
    exit 1
fi

# Global Options
VERBOSE="false"

do_consolidate () {
    local SOURCE="$1"
    local DEST="$2"
    local BASE="$3"

    echo "Consolidating $SOURCE into $DEST with base $BASE"

    rsync \
	--archive \
	--partial \
	--progress \
	--verbose \
	--delete \
	--link-dest="$BASE" \
	"$SOURCE" "$DEST"
}

do_consolidate_backups() {

    # Consolidates existing incremental backups into new directory tree.
    # Recreates them in-order using the incremental approach.
    local SOURCE="$1"
    local DEST="$2"

    mkdir -p "$DEST"

    # Check consolidation target before writing...
    echo "Checking for CONSOLIDATION_TARGET_OK"
    PROTECTED_FILE="$DEST/CONSOLIDATION_TARGET"
    if [ ! -f "${PROTECTED_FILE}_OK" ]; then
	echo "You need to rename CONSOLIDATION_TARGET to CONSOLIDATION_TARGET_OK to enable consolidation to this location."
	# Assert consolidation destination is valid.
	# Check for presence of ok file.
	if [ ! -f "$PROTECTED_FILE" ]; then
	    echo "Rename this file to CONSOLIDATION_TARGET_OK to enable targeting this location." > "$PROTECTED_FILE"
	fi
	exit 1
    fi

    cd "$SOURCE"
    backupdirs=(backup-*/) # grab all backup directories
    echo "Backup dirs:"
    echo "${backupdirs[@]}"
    for i in "${!backupdirs[@]}"; do
	echo "Processing: ${backupdirs[$i]}"
	if (( i == 0 )); then
	    # soft-duplicate base directory into the consolidated result set
	    # Use hard links to avoid duplicating disk usage
	    echo "Duplicating base directory using hard links: $SOURCE/${backupdirs[$i]} -> $DEST/${backupdirs[$i]}"
	    rsync \
		--archive \
		--link-dest="$SOURCE/${backupdirs[$i]}" \
		"$SOURCE/${backupdirs[$i]}" \
		"$DEST/${backupdirs[$i]}"
	    continue
	fi
	local prev=$((i-1))
	local BASE=""
	BASE="$DEST/${backupdirs[$prev]}"
	do_consolidate \
	    "$SOURCE/${backupdirs[$i]}" \
	    "$DEST/${backupdirs[$i]}" \
	    "$BASE"
    done
}

do_incremental_backup() {

    local DATE_TAG=""
    DATE_TAG=$(date "+%Y-%m-%dT%H-%M-%S")

    local SOURCE="$1"
    local DEST="$2"

    # NOTE: This has to be run on the target machine?
    # Can I make it so it works across the network?
    # Target should be able to be a remote machine.
    # Pull backups vs push backups.
    if [ ! -d "$DEST" ]; then
	# Currently this just works for pull backups.
	# Would be nice if it worked for push backups.
	# NOTE: Pull backups seem safer from an access point of view.
	# Maybe its fine to leave this as it is?
	[[ "$VERBOSE" == "true" ]] && echo "Debug: Creating destination directory..."
	mkdir -p "$DEST" && echo "Directory created." || echo "Error: Can't create directory." && return 1
    fi

    [ ! -e "$DEST/README.md" ] && echo "Generated backups using backup script. See Liam's Toolkit. https://github.com/liamtbrand/toolkit" > "$DEST/README.md"

    [[ "$VERBOSE" == "true" ]] && echo "Debug: Writing rsync_ignore file..."
    cat > "$DEST/rsync_ignore" << EOF
.DS_Store
.Spotlight-V100
.DocumentRevisions-V100
.TemporaryItems
.CFUserTextEncoding
EOF

# TODO: Figure out if it is necessary to use "sudo rsync"
# I have a feeling it may be necessary simply in order to copy everything on the machine for machine wide backups.
# Probably need some kind of flag to indicate if the backup is a root level backup or just a local user directory.

    rsync \
	--archive \
	--compress \
	--partial --progress \
	--link-dest="$DEST/latest" \
	--log-file="$DEST/backup-$DATE_TAG.log" \
	--exclude-from="$DEST/rsync_ignore" \
	--rsync-path="sudo rsync" \
	"$SOURCE" "$DEST/backup-$DATE_TAG"

    rm -f "$DEST/latest"
    ln -s "$DEST/backup-$DATE_TAG" "$DEST/latest"
}

do_mirror_backup () {
    local SOURCE="$1"
    local DEST="$2"

    # Assert target is a directory
    if [ ! -d "$DEST" ]; then
	echo "Directory target could not be acquired! Abort."
	exit 1
    fi
    echo "Target: $DEST"

    echo "Checking for BACKUP_TARGET_OK"
    PROTECTED_FILE="$DEST/BACKUP_TARGET"
    if [ ! -f "${PROTECTED_FILE}_OK" ]; then
	echo "You need to rename BACKUP_TARGET to BACKUP_TARGET_OK to enable mirroring to this location."
	# Assert backup destination is valid.
	# Check for presence of ok file.
	if [ ! -f "$PROTECTED_FILE" ]; then
	    echo "Rename this file to BACKUP_TARGET_OK to enable targeting this location." > "$PROTECTED_FILE"
	fi
	exit 1
    fi

    rsync \
	--verbose \
	--archive \
	--compress \
	--partial \
	--progress \
	--delete \
	--dry-run \
	--filter="P BACKUP_TARGET_OK" \
	"$SOURCE" \
	"$DEST"
}

help () {
    cat <<EOF
Backup tool. Make incremental backups.
The backup tool makes a pull based mirror or incremental backup.

Usage: backup MODE --from SRC --to DEST

You must specify a MODE along with the --from and --to options.

There are three modes: mirror, incremental and consolidate.

  --mirror      - This mode mirrors the contents of source to destination.

  --incremental - This mode creates a structured incremental backup of source to destination.

  --consolidate - This mode consolidates existing structured incremental backups from source into destination.
                  Note: This mode can be used to relocate backups onto a different disk, recreating hard-links.

    Consolidation walks through existing incremental backups and consolidates them into a target location.
    This is useful to fix unlinked backups or to transfer a series of incremental backups a new location.

Usage examples:

  backup --incremental --from user@machine:'/path/to/source/data' --to /path/to/destination

  backup --mirror --from user@machine:'/path/to/source/data' --to /path/to/destination

  backup --consolidate --from /path/to/incremental/backups --to /path/to/incremental/backups/consolidation

Note:
  You must configure ssh keys for authenticating with remote machines.

Warnings:
  Take care to correctly quote the directory path. Notably whether or not to include a trailing slash. See rsync man pages for help.

Debugging:
  Known footgun with paths on remote machines. Check you've correctly quoted remote paths!
EOF
}

backup () {

    local SOURCE=""
    local DEST=""
    local MODE=""

    while [[ $# -gt 0 && "$1" == -* ]]; do
	case "$1" in
	    --incremental)
		MODE="incremental"
		shift
		;;
	    --mirror)
		MODE="mirror"
		shift
		;;
	    --consolidate)
		MODE="consolidate"
		shift
		;;
	    --from)
		SOURCE="$2"
		shift 2
		;;
	    --to)
		DEST="$2"
		shift 2
		;;
	    -v|--verbose)
		VERBOSE="true"
		shift
		;;
	    -h|--help)
		help
		exit 0
		;;
	    *)
		echo "Unknown option: $1"
		exit 1
		;;
	esac
    done

    [[ -z "$SOURCE" ]] && { echo "Error: --from path is required."; exit 1; }
    [[ -z "$DEST" ]] && { echo "Error: --to path is required."; exit 1; }

    case "$MODE" in
	incremental)
	    do_incremental_backup "$SOURCE" "$DEST"
	    ;;
	mirror)
	    do_mirror_backup "$SOURCE" "$DEST"
	    ;;
	consolidate)
	    do_consolidate_backups "$SOURCE" "$DEST"
	    ;;
	*)
	    echo "Specify a backup mode: --incremental or --mirror"
	    exit 1
	    ;;
    esac
}

backup "$@"
