#!/usr/bin/env bash

# Config tool to manage and update shell configuration
# Used to manage my dotfiles - general config
# These are stored in the config repo.
# Tool also managed modules installed. ?
# Tool also used to manage toolkit itself.
#	-> Moving this responsibility to the toolkit tool.
#
# Try keep as little config as possible in the regular configuration files. (.zshrc)
# This is because various systems have customised configuration.
# It is easier to manage if the configuration is sourced from another file
# than trying to resolve conflicts manually each time.
#
# This tool should really change so its responsibility
# is applying configuration profiles. That is, configure applications
# with user specific settings and customization.
# The tools themselves should come from toolkit.
#
# I'm thinking a workflow like:
# - Update tools using toolkit.
#	-> Includes this config tool
# - Update and apply profile configuration using config tool.
#
# The separation of concerns enables installing tools via the toolkit without
# requiring all of the profile information config would provide.
# The enables using tools and scripts on endpoints without needing
# to use the same dotfiles everywhere. config would not always be necessary.

# The repo names are in order of detection.
# Some systems use dotfiles.git others use config.git.

__private_config_git () {
	/usr/bin/git --git-dir="$CONFIG_REPO_PATH" --work-tree="$HOME" "${@:1}"
}

# To bootstrap config, simply copy this script and execute "config init"
__private_config_init () {
	# Clone git repo into home directory	
	
	# Don't show untracked files
	__private_config_git config --local status.showUntrackedFiles no

}

config () {
	case "$1" in
		"git")
			__private_config_git "${@:2}"
			;;
		"init")
			__private_config_init
			;;
		*)
			echo "Config tool. Configuration repo: $CONFIG_REPO_PATH"
			echo "Usage: config git <command>"
			;;
	esac
}

config "$@"
