#!/usr/bin/env bash
set -euo pipefail

# Tool to mirror repositories
# Tag: 1CE519C7-E318-4F01-B4FB-75219D34861D

# Requirements:
# - yq - Used for parsing yaml files

MIRRORS_DIR="$HOME/mirrors"
# The mirrors file contains a list of mirror name + url
MIRRORS_FILE="$HOME/mirrors/mirrors.yaml"

assert_mirrors_file_exists () {
	if [ ! -f "$MIRRORS_FILE" ] ; then
		echo "No mirrors file found"
		exit 1
	fi
}

mirrors_update_mirror () {
	local item_yaml=""
	item_yaml="$1"
	echo ""
	echo "Processing yaml entry:"
	echo "$item_yaml"
	echo "---"

	local name=""
	name=$(yq '.name' <<< "$item_yaml")
	if [[ -z "$name" ]]; then
		echo "WARNING: No name found for mirror. Skipping entry."
		return
	fi

	# Read path from yaml
	local path=""
	path=$(yq '.path // ""' <<< "$item_yaml")
	# Default to name.git if path is not explicitly set
	path=${path:-"${MIRRORS_DIR}/${name}.git"}

	if [[ ! -d "$path" ]]; then
		echo "Mirror repo doesn't exist yet at: $path"
		echo "Attempting to create it..."
		local url=""
		url=$(yq '.url' <<< "$item_yaml")
		if [[ -z "$url" ]]; then
			echo "WARNING: No url found for mirror. Skipping entry."
			return
		fi
		echo "DRY: git clone --mirror $url $path"
		#git clone --mirror "$url" "$path"
		return
	fi
	
	echo "Updating mirror at: $path"
	git -C "$path" remote update
}

set_mirrors_paths () {
	MIRRORS_FILE="${1:-"${MIRRORS_FILE}"}"
	assert_mirrors_file_exists
	local path=""
	# Extract optional mirrors path
	path="$(yq '.path // ""' "$MIRRORS_FILE")"
	if [[ -z "$path" ]]; then
		# Default to parent directory if empty...
		path="$(dirname "$MIRRORS_FILE")"
	fi
	if [[ ! -d "$path" ]]; then
		echo "Can't locate specified path: $path"
		echo "Note: You must manually create the target directory."
		echo "Check the mirrors file at: $MIRRORS_FILE"
		echo "Aborting."
		exit 1
	fi

}

mirrors_update () {
	set_mirrors_paths "$1"
	assert_mirrors_file_exists
	while IFS= read -r -d '' item_yaml; do
		mirrors_update_mirror "$item_yaml"
	done < <(yq -o=y -0 '.mirrors.[]' "$MIRRORS_FILE")
}

mirrors_list () {
	set_mirrors_paths "${@:1}"
	echo "MIRRORS_FILE=$MIRRORS_FILE"
	echo "MIRRORS_DIR=$MIRRORS_DIR"
	assert_mirrors_file_exists
	while IFS= read -r -d '' item_yaml; do
		echo "$item_yaml"
		name=$(yq '.name' <<< "$item_yaml")
		echo ""
	done < <(yq -o=y -0 '.mirrors.[]' "$MIRRORS_FILE")
}

mirrors_edit () {
	"$EDITOR" "$MIRRORS_FILE"
}

mirrors () {
	local command
	command="${1:-help}"
	case "$command" in
		"list")
			mirrors_list
			;;
		"edit")
			mirrors_edit
			;;
		"update")
			mirrors_update "${@:2}"
			;;
		"help")
			echo "Git mirrors tool. Use this to keep organised mirrors of many git repositories."
			echo ""
			echo "mirrors edit       - Open mirrors file for editing"
			echo "mirrors update     - Update the mirrors by fetching changes over network"
			echo "mirrors list       - List mirrors"
			echo "mirrors help       - Show this help"
			;;
		*)
			echo "Unknown command"
			;;
	esac
}

mirrors "$@"
