#!/usr/bin/env bash
set -euo pipefail

# Git repository management tool
# Use this tool to manage git repositories on your machine.

# Preconditions
#__private_repos_assert_dependencies() {
#	command -v git >/dev/null 2>&1 || { echo >&2 "Error: Git is not installed."; exit 1 }
#	command -v find >/dev/null 2>&1 || { echo >&2 "Error: find is not installed."; exit 1 }
#}

#__private_repos_assert_dependencies

# TODO: Make all paths use the full path. Should not be relative paths.

# === CONFIG SETTINGS ===

REPOS_PATHS_FILE=~/.config/repos/paths

# The ignore file lists out paths to ignore when processing repos
# TODO: Enable this
REPOS_IGNORE_FILE=$HOME/.config/repos/ignore

# === Helper Functions ===

__private_repos_get_rel_path () {
	# $1 : relative filename
	abs_path="$(cd "$(dirname -- "$1")" && pwd)/$(basename -- "$1")"
	rel_path="~/${abs_path#$HOME/}"	
	rel_path="${rel_path%/}"
	echo "$rel_path"
}

__private_repos_get_abs_path () {
	abs_path="$(cd "$(dirname -- "$1")" && pwd)/$(basename -- "$1")"
	echo "$abs_path"
}

# === Commands ===

__private_repos_fetch () {
	
	while IFS= read -r; do
		repo="$REPLY"
		repo="${repo/#\~/$HOME}"

		printf "\\033[36m=== %s ===\\033[0m" "$repo"

		git -C "$repo" fetch --dry-run --verbose
	done < "$REPOS_PATHS_FILE"
}

__private_repos_goto () {
	selected="$(__private_repos_list | fzf)"
	selected="${selected/#\~/$HOME}"  # Replace ~ with $HOME
	cd "$selected"
}

# Adds a repository to the paths file.
# Takes a relative path?
# TODO: Make sure this one can handle any kind of path thrown at it...
__private_repos_add () {
	rel_path="$(__private_repos_get_rel_path "$1")"
	abs_path="$(__private_repos_get_abs_path "$1")"
	if [ -d "$abs_path/.git" ] && [ -d "$abs_path/.git/annex" ]; then
		echo "Skipping add because this appears to be a git-annex repo."
	else
		echo "Adding repo to paths file: $REPOS_PATHS_FILE"
		grep -qx "$rel_path" "$REPOS_PATHS_FILE" && echo "Skipping... Already present?" || echo "$rel_path" >> "$REPOS_PATHS_FILE"	
		# Keep it sorted.
		sort -o "$REPOS_PATHS_FILE" "$REPOS_PATHS_FILE"
	fi
}

__private_repos_repo_is_in_paths_file () {
	repo="$1"
	rel_path="$(__private_repos_get_rel_path "$repo")"
	grep -qx "$rel_path" "$REPOS_PATHS_FILE"
}

# Search for repositories relative to the current directory.
__private_repos_find () {
	echo "finding repos..."

	found=()
	while IFS= read -r -d ''; do
		repo_dir="$(dirname -- "$REPLY")"
		repo_dir="${repo_dir%/.}"
		found+=("$repo_dir")
	done < <(find . -name .git -print0)

	echo ""
	known=()
	unknown=()

	known_to_mr=()
	unknown_to_mr=()
	local MR_FILE="$HOME/.mrconfig"
	
	for repo in "${found[@]}"; do
		rel_path="$(__private_repos_get_rel_path "$repo")"
		grep -qx "$rel_path" "$REPOS_PATHS_FILE" && known+=("$rel_path") || unknown+=("$rel_path")

		mr_path="${rel_path:2}"
		grep -qx "$mr_path" "$MR_FILE" && known_to_mr+=("$rel_path") || unknown_to_mr+=("$rel_path")
	done

	echo "known:"
	for repo in "${known[@]}"; do
		echo "	$repo"	
	done

	echo "unknown:"
	for repo in "${unknown[@]}"; do
		echo "	$repo"
	done

	echo "known_to_mr:"
	for repo in "${known_to_mr[@]}"; do
		echo "	$repo"
	done

	echo "unknown_to_mr:"
	for repo in "${unknown_to_mr[@]}"; do
		echo "	$repo"
	done

	# TODO: Show repos that are already registered.
}

# List out registered repositories.
__private_repos_list () {
	cat "$REPOS_PATHS_FILE"
}

# Show the status of the registered repositories.
__private_repos_status_long () {

	while IFS= read -r; do
		repo="$REPLY"
		repo="${repo/#\~/$HOME}"  # Replace ~ with $HOME
		echo ""
		printf "\\033[36m=== %s ===\\033[0m" "$repo"

		git -C "$repo" remote -v

		# NOTE: Not clear if the simplify-by-decoration flag here is appropriate. Maybe it will miss things?
		git -C "$repo" log --branches --not --remotes --oneline --simplify-by-decoration --decorate --graph
		#[ -z "$local_only" ] && echo "$local_only" || true
		
		#echo "branches:"
		#echo "$(git -C "$repo" branch -v)"
		#echo "remote branches:"	
		#echo "$(git -C "$repo" branch -v -r)"
		#echo "remotes:"
		#echo "$(git -C "$repo" remote -v)"
		#echo ""
		echo "status:"
		git -C "$repo" status --short --branch
		echo ""
		#echo "What just happened?"
		#echo "$(git -C "$repo" log --graph -3 --oneline)"
		#echo ""
		#echo "What am I doing now?"
		#echo "$(git -C "$repo" status --short --branch)"
		#echo ""
		#echo "What is everything I'm working on?"
		#echo "$(git -C "$repo" branch -vv)"
		#echo ""
	done < "$REPOS_PATHS_FILE"	
}

__private_repos_status_of_repo () {

	# NOTE: Types of status lines are:
	# - Local changes that haven't been committed yet.
	# - Local commits that haven't been pushed
	# - Remote commits that haven't been pulled
	# The diff of local/remote are pairings for all remotes that are configured.
	# So, one remote named origin results in 2 local/remote entries.
	# You can think of this as outgoing and incoming for each remote.

	local repo="$1"
	#echo "$repo"
	#echo "args: ${@:1}"
	
	#skip_ok=false
	#if [ "$2" = "--skip-ok" ]; then
	#	skip_ok=true # Should we skip ok repos
	#fi

	local fetch=false
	local dirty_only=false
	
	for arg in "${@:2}"; do
		#echo "Processing: $arg"
		case "$arg" in
			"--dirty")
				dirty_only=true
				;;
			"--fast")
				fetch=false
				;;
			"--fetch")
				fetch=true
				;;
			*)
				echo "Ignoring unknown argument $arg"
				;;
		esac	
	done


	# Process the local changes first. This tells us if we have a dirty or clean repo.

	local changes=""
	changes="$(git -C "$repo" status --porcelain)"
	local is_clean=true	
	if [ -n "$changes" ]; then
		is_clean=false
	fi
	
	local remotes=($(git -C "$repo" remote))
	if [ -z "$remotes" ]; then
		is_clean=false # no remotes. mark dirty ? need to show this isn't in a good state.
	fi

	if [ $dirty_only = false ] || [ $is_clean = false ]; then

		local clean_status=""
		clean_status=$($is_clean && printf "\033[32mCLEAN\033[0m" || printf "\033[31mDIRTY\033[0m")
		echo "$clean_status $repo"

		# Begin processing remote changes. Compare branches with what is on the various remotes.
		
		# NOTE: We'll fetch all changes we can first...
		if [ $fetch = true ]; then
			git -C "$repo" fetch --all
		fi

		if [ -z "$remotes" ]; then
			printf "\033[31mwarn\033[0m No remotes. You should configure an upstream remote."	
		fi

		for remote in "${remotes[@]}"; do
			
			local commits=""
			commits="$(git -C "$repo" log --branches --not --remotes --oneline --simplify-by-decoration --decorate --graph)"

			if [ -n "$commits" ]; then
				printf "- remote: %s is \033[31mmissing\033[0m:" "$remote"
				echo "$commits"
			fi	

		done

		local status_sb=""
		status_sb="$(git -C "$repo" status --short --branch)"

		# Only print if branch is behind remote
		if grep -q "\[behind " <<< "$status_sb"; then
			echo "$status_sb"
		fi

	fi

}

__private_repos_status () {
	local counter=0
	while IFS= read -r; do
		local repo="$REPLY"
		local repo="${repo/#\~/$HOME}"
		__private_repos_status_of_repo "$repo" "$@"
		counter=$((counter + 1))
	done < "$REPOS_PATHS_FILE"

	echo ""
	echo "Done. Reported on the status of $counter repos."
}

__private_repos_fsck_repo () {
	local repo="$1"
	echo "$repo"
	git -C "$repo" fsck
}

__private_repos_fsck () {
	while IFS= read -r; do
		local repo="$REPLY"
		local repo="${repo/#\~/$HOME}"
		__private_repos_fsck_repo "$repo"
	done < "$REPOS_PATHS_FILE"
}

__private_repos_help () {
	echo "Repos tool. Show the status of all the repos on the system."
	echo "Repositories are stored as a list of paths in: ${REPOS_PATHS_FILE/#$HOME/~}"
	echo "Use this tool to keep repositories fully in sync with upstream."
	echo ""
	echo "repos add <path>     - Add a repository to the repos list"
	echo "repos find           - Find repos nearby (searches 3 levels deep in current directory)"
	echo "repos list           - List repos in the repository list"
	echo "repos goto           - Go to one of the repos. Select using fzf."
	echo "repos status         - Show the status of all the registered repositories"
	echo ""
}

# When there is an unknown command,
# notify the user that the command is unknown,
# and display the help page.
__private_repos_unknown_command () {
	echo "Unknown command: $1"
	echo ""
	__private_repos_help
}

__private_repos_audit_policy_origin_required () {
	repo="$1"
	local REPO_URL=""
	REPO_URL="$(git -C "$repo" config --get remote.origin.url)"
	if [ -z "$REPO_URL" ] ; then
		echo "Warning: Policy violation. Repo: $repo does not have an origin remote set."
		echo "Policy: All repositories have an origin remote set."
	fi
}

ask_yes_no () {
	while true; do
		# Note: /dev/tty redirect important:
		# This could be inside another read while loop...
		read -r -p "$1 [y/n]: " yn < /dev/tty
		case $yn in
			[Yy][Ee][Ss]|[Yy] ) return 0;;
			[Nn][Oo]|[Nn] ) echo "Aborted."; return 1;;
			*) echo "Please answer yes or no.";;
		esac
	done
}

__private_repos_audit_policy_all_repos_are_registered_check_repo_is_registered () {
	repo="$1"
	echo "Policy check for: $repo"
	if ! __private_repos_repo_is_in_paths_file "$repo" ; then
		echo "Warning: Policy violation. Repo: $repo is not in paths file."
		if ask_yes_no "Do you want to add $repo to the paths file?"; then
			echo "Adding $repo to the paths file..."
			__private_repos_add "$repo"
		else
			echo "Skipping violation... Warning: You should fix this."	
		fi
	fi
}

_should_skip_repo () {
	repo="$1"
	grep -qf "$REPOS_IGNORE_FILE" <<< "$repo"
}

__private_repos_audit_policy_all_repos_are_registered () {
	echo "Policy: All repositories are registered with the repos tool."

	# Find repositories on system...
	# Check these are all registered with the repos tool...
	# Report anything that isn't registered.
	echo "Searching for repositories..."

	while IFS= read -r -d ''; do
		repo_dir="$(dirname -- "$REPLY")"
		repo="${repo_dir%/.}"
		# If file in ignore file, ignore it...
		if _should_skip_repo "$repo"; then
			echo "Skipping repo: $repo"
			continue
		fi
		__private_repos_audit_policy_all_repos_are_registered_check_repo_is_registered "$repo"
	done < <(find . -name .git -print0)
}

__private_repos_audit_policy_all_paths_in_paths_file_are_absolute () {
	while IFS= read -r; do
		local repo="$REPLY"
	done < "$REPOS_PATHS_FILE"
}

repos_audit () {
	echo "Running git repo audit..."

	#__private_repos_audit_policy_all_paths_in_paths_file_are_absolute

	# Audit registration policies
	__private_repos_audit_policy_all_repos_are_registered

	# Audit registered repositories
	while IFS= read -r; do
		# Read path to repo
		# TODO: Use yield approach to format the read nicely
		local repo="$REPLY"
		repo="${repo/#\~/$HOME}"  # Replace ~ with $HOME
		# TODO: Abort if repo path isn't correct?

		if _should_skip_repo "$repo"; then
			echo "Skipping repo: $repo"
			continue
		fi

		echo "Evaluating: $repo"

		# Check compliance against policies
		__private_repos_audit_policy_origin_required "$repo"
	done < "$REPOS_PATHS_FILE"
}

repos () {
	local command
	command="${1:-help}"
	case "$command" in
		"find")
			__private_repos_find "${@:1}"
			;;
		"list")
			__private_repos_list
			;;
		"add")
			__private_repos_add "${@:2}"
			;;
		"goto")
			__private_repos_goto
			;;
		"fetch")
			__private_repos_fetch
			;;
		"fsck")
			__private_repos_fsck
			;;
		"status")
			__private_repos_status "${@:2}"
			;;
		"audit")
			repos_audit
			;;
		"help")
			__private_repos_help "${@:2}"
			;;
		*)
			__private_repos_unknown_command "${@:2}"
			;;
	esac
}

repos "$@"
